-- require"fidget".setup{
--   text = {
--     spinner = "bouncing_ball",         -- animation shown when tasks are ongoing
--     done = "✔",               -- character shown when all tasks are complete
--     commenced = "Ti Acalma que ta carregando",    -- message shown when task starts
--     completed = "Agora foi, vemtibora",  -- message shown when task completes
--   }
-- }
