local opt = vim.opt
opt.autoindent = true
opt.cindent = true
opt.cinwords = "if,elif,else,for,while,try,except,finally,def,class,with"
opt.colorcolumn = "80"
opt.copyindent = true
opt.expandtab = true
opt.formatoptions = "jntcoql"
opt.shiftwidth = 4
opt.softtabstop = 4
opt.tabstop = 8
